/**
 * Seed Script: Reads docs/zonos-onboarding-template-export.json
 * and generates SQL seed migration for the universal template.
 *
 * Usage: npx tsx src/scripts/seed-template.ts
 * Output: supabase/migrations/20260313000001_seed_universal_template.sql
 */

import * as fs from 'fs';
import * as path from 'path';

const INPUT_PATH = path.join(__dirname, '../../docs/zonos-onboarding-template-export.json');
const OUTPUT_PATH = path.join(__dirname, '../../supabase/migrations/20260313000001_seed_universal_template.sql');

type IRawWidget = {
  id: string;
  type: string;
  orderTree: string;
  hiddenByDefault: boolean;
  fieldType?: string;
  key?: string;
  label?: string;
  required?: boolean;
  config?: {
    items?: Array<{ id: string; name: string }>;
    options?: Array<{ id: string; name: string }>;
    format?: string;
    placeholder?: string;
    url?: string;
    src?: string;
  };
  content?: string;
  constraints?: Record<string, unknown>;
  deleted?: boolean;
  url?: string;
  description?: string;
  file?: {
    url?: string;
    originalName?: string;
    name?: string;
  };
  service?: string;
  serviceCode?: string;
};

type IRawTask = {
  id: string;
  name: string;
  orderTree: string;
  taskType: string;
  stop: boolean;
  hiddenByDefault: boolean;
  groupId: string;
  status: string;
  widgetCount: number;
  widgets: IRawWidget[];
};

type IRawConditionalRule = {
  id: string;
  orderTree: string;
  operator: string;
  operand: {
    data: {
      operator: string;
      conditions: Array<{
        operator: string;
        conditions: Array<{
          formFieldWidgetGroupId: string;
          operator: string;
          operandValue?: { value: string };
          operandType: string;
        }>;
      }>;
    };
    operandType: string;
  };
  hidden: boolean;
  taskTemplateGroupIds: string[];
  widgetGroupIds: string[];
};

type IRawDueDateRule = {
  id: string;
  targetTaskTemplateGroup: { id: string };
  sourceType: string;
  formFieldWidgetGroup?: { id: string };
  offsetDirection: string;
  dueOffset: {
    years: number;
    months: number;
    days: number;
    hours: number;
    minutes: number;
    seconds: number;
    weeks: number;
  };
  workdaysOnly: boolean;
};

type IRawAssignmentRule = {
  id: string;
  targetTaskTemplateGroup: { id: string };
  sourceType: string;
  sourceFormFieldWidgetGroup?: { id: string };
};

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

function orderTreeToIndex(orderTree: string): number {
  const parts = orderTree.split('.');
  let idx = 0;
  for (let i = 0; i < parts.length; i++) {
    const val = parseInt(parts[i], 36);
    idx = idx * 100 + val;
  }
  return idx;
}

/** Map PS field types to our widget_type enum */
function mapFieldType(psFieldType: string): string {
  const mapping: Record<string, string> = {
    Text: 'text',
    Textarea: 'textarea',
    RichText: 'richtext',
    Email: 'email',
    Url: 'url',
    Select: 'select',
    MultiSelect: 'multi_select',
    MultiChoice: 'multi_choice',
    Date: 'date',
    File: 'file',
    Hidden: 'hidden',
    SendRichEmail: 'send_rich_email',
  };
  return mapping[psFieldType] || 'text';
}

/** Map PS operators to our condition_operator enum */
function mapOperator(psOp: string): string {
  const mapping: Record<string, string> = {
    Is: 'is',
    IsNot: 'is_not',
    Contains: 'contains',
    HasNoValue: 'has_no_value',
  };
  return mapping[psOp] || 'is';
}

function getCurrentSection(tasks: IRawTask[], index: number): string {
  // Walk backwards to find the nearest section header (task with ⭐)
  for (let i = index; i >= 0; i--) {
    if (tasks[i].name.startsWith('⭐')) {
      return tasks[i].name.replace(/^⭐\s*/, '').replace(/:?\s*$/, '');
    }
  }
  return 'General';
}

function main() {
  const raw = JSON.parse(fs.readFileSync(INPUT_PATH, 'utf-8'));
  const tasks: IRawTask[] = raw.tasks;
  const conditionalRules: IRawConditionalRule[] = raw.conditionalLogicRules || [];
  const dueDateRules: IRawDueDateRule[] = raw.dueDateRules || [];
  const assignmentRules: IRawAssignmentRule[] = raw.taskAssignmentRules || [];

  // Build widget groupId -> key mapping for resolving rules
  const widgetGroupToKey = new Map<string, string>();
  const widgetGroupToTaskGroup = new Map<string, string>();
  for (const task of tasks) {
    for (const w of task.widgets) {
      if (w.key) {
        widgetGroupToKey.set(w.id, w.key);
      }
      widgetGroupToTaskGroup.set(w.id, task.groupId);
    }
  }

  const lines: string[] = [];
  lines.push('-- Auto-generated seed data from Process Street template export');
  lines.push('-- Generated by src/scripts/seed-template.ts');
  lines.push('-- DO NOT EDIT MANUALLY');
  lines.push('');

  // Delete existing seed data
  lines.push('-- Clean existing seed data');
  lines.push("DELETE FROM task_field_values;");
  lines.push("DELETE FROM tasks;");
  lines.push("DELETE FROM template_rules;");
  lines.push("DELETE FROM template_widgets;");
  lines.push("DELETE FROM template_tasks;");
  lines.push("DELETE FROM projects;");
  lines.push("DELETE FROM templates;");
  lines.push('');

  // Create template
  const templateId = 'a0000000-0000-0000-0000-000000000001';
  lines.push('-- Template');
  lines.push(`INSERT INTO templates (id, name, description, is_active) VALUES (`);
  lines.push(`  '${templateId}',`);
  lines.push(`  '${escapeSQL(raw._meta.templateName)}',`);
  lines.push(`  '${escapeSQL(raw._meta.description || '')}',`);
  lines.push(`  true`);
  lines.push(`);`);
  lines.push('');

  // Create template tasks
  lines.push('-- Template Tasks');
  const taskGroupToUUID = new Map<string, string>();

  for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];
    const section = getCurrentSection(tasks, i);
    const orderIndex = i;
    // Generate deterministic UUID from index
    const uuid = `b${String(i).padStart(7, '0')}-0000-0000-0000-000000000001`;
    taskGroupToUUID.set(task.groupId, uuid);

    const isHeader = task.name.startsWith('⭐');
    const assigneeType = task.name.includes('merchant') || task.name.includes('Merchant') ? 'merchant' : 'ob';
    const taskType = isHeader ? 'section_header' : 'standard';

    lines.push(`INSERT INTO template_tasks (id, template_id, title, section, order_index, assignee_type, task_type, hidden_by_default, is_stop_gate, ps_group_id) VALUES (`);
    lines.push(`  '${uuid}',`);
    lines.push(`  '${templateId}',`);
    lines.push(`  '${escapeSQL(task.name)}',`);
    lines.push(`  '${escapeSQL(section)}',`);
    lines.push(`  ${orderIndex},`);
    lines.push(`  '${assigneeType}',`);
    lines.push(`  '${taskType}',`);
    lines.push(`  ${task.hiddenByDefault},`);
    lines.push(`  ${task.stop},`);
    lines.push(`  '${escapeSQL(task.groupId)}'`);
    lines.push(`);`);
  }
  lines.push('');

  // Create template widgets (ALL types, not just form fields)
  lines.push('-- Template Widgets');
  let widgetIndex = 0;

  /** Map PS content widget types to our widget_type enum */
  function mapContentType(psType: string): string {
    const mapping: Record<string, string> = {
      Text: 'text_content',
      Image: 'image',
      Video: 'video',
      Embed: 'embed',
      CrossLink: 'cross_link',
      File: 'file',
    };
    return mapping[psType] || 'text_content';
  }

  for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];
    const taskUUID = taskGroupToUUID.get(task.groupId);
    if (!taskUUID) continue;

    for (let j = 0; j < task.widgets.length; j++) {
      const w = task.widgets[j];
      if (w.deleted) continue;

      const widgetUUID = `c${String(widgetIndex).padStart(7, '0')}-0000-0000-0000-000000000001`;
      widgetIndex++;

      let widgetType: string;
      let key: string | null = null;
      let label: string | null = null;
      let isRequired = false;
      let placeholder: string | null = null;
      let options = '[]';
      const hidden = w.hiddenByDefault || false;
      const metadata: Record<string, unknown> = {};

      if (w.type === 'FormField') {
        // Form field widget
        widgetType = mapFieldType(w.fieldType || 'Text');
        if (w.config?.format === 'RichText') widgetType = 'richtext';
        key = w.key || null;
        label = w.label || null;
        isRequired = w.required || false;
        placeholder = w.config?.placeholder || null;

        // Extract options from config
        const items = w.config?.items || w.config?.options || [];
        if (items.length > 0) {
          options = JSON.stringify(items.map((item: { id?: string; name: string }) => ({ value: item.name, label: item.name })));
        }
      } else {
        // Content widget (Text, Image, Video, Embed, File, CrossLink)
        widgetType = mapContentType(w.type);

        if (w.type === 'Text' && w.content) {
          metadata.content = w.content;
        } else if (w.type === 'Image') {
          metadata.url = w.file?.url || w.url || '';
          metadata.alt = w.file?.originalName || w.file?.name || '';
        } else if (w.type === 'Video') {
          metadata.url = w.file?.url || w.url || '';
          metadata.service = w.service || '';
          metadata.serviceCode = w.serviceCode || '';
        } else if (w.type === 'Embed') {
          metadata.url = w.url || '';
        } else if (w.type === 'File') {
          metadata.url = w.file?.url || w.url || '';
          metadata.name = w.file?.originalName || w.file?.name || '';
        }
      }

      const metadataJSON = Object.keys(metadata).length > 0
        ? `'${escapeSQL(JSON.stringify(metadata))}'`
        : "'{}'";

      lines.push(`INSERT INTO template_widgets (id, template_task_id, key, label, widget_type, order_index, is_required, hidden_by_default, options, placeholder, metadata, ps_group_id) VALUES (`);
      lines.push(`  '${widgetUUID}',`);
      lines.push(`  '${taskUUID}',`);
      lines.push(`  ${key ? `'${escapeSQL(key)}'` : 'NULL'},`);
      lines.push(`  ${label ? `'${escapeSQL(label)}'` : 'NULL'},`);
      lines.push(`  '${widgetType}',`);
      lines.push(`  ${j},`);
      lines.push(`  ${isRequired},`);
      lines.push(`  ${hidden},`);
      lines.push(`  '${escapeSQL(options)}',`);
      lines.push(`  ${placeholder ? `'${escapeSQL(placeholder)}'` : 'NULL'},`);
      lines.push(`  ${metadataJSON},`);
      lines.push(`  '${escapeSQL(w.id)}'`);
      lines.push(`);`);
    }
  }
  lines.push('');

  // Create conditional rules
  lines.push('-- Conditional Rules');
  for (let i = 0; i < conditionalRules.length; i++) {
    const rule = conditionalRules[i];
    const ruleUUID = `d${String(i).padStart(7, '0')}-0000-0000-0000-000000000001`;

    // Resolve conditions
    const compoundConditions = {
      logic: 'or' as const,
      conditions: rule.operand.data.conditions.map(orGroup => ({
        logic: 'and' as const,
        conditions: orGroup.conditions.map(c => ({
          widget_key: widgetGroupToKey.get(c.formFieldWidgetGroupId) || c.formFieldWidgetGroupId,
          operator: mapOperator(c.operator),
          value: c.operandValue?.value ?? null,
        })),
      })),
    };

    // Resolve target tasks
    const targetTaskIds = rule.taskTemplateGroupIds
      .map(gid => taskGroupToUUID.get(gid))
      .filter(Boolean);
    const targetTaskIdsSQL = targetTaskIds.length > 0
      ? `ARRAY[${targetTaskIds.map(id => `'${id}'`).join(',')}]::uuid[]`
      : `'{}'::uuid[]`;

    // Target widgets stay as PS group IDs (matched at runtime via ps_group_id)
    const targetWidgetIds = rule.widgetGroupIds;
    const targetWidgetIdsSQL = `'{}'::uuid[]`; // Widget IDs resolved at runtime

    const action = rule.hidden ? 'hide' : 'show';

    lines.push(`INSERT INTO template_rules (id, template_id, rule_type, action, target_task_ids, target_widget_ids, compound_conditions, ps_rule_id, metadata) VALUES (`);
    lines.push(`  '${ruleUUID}',`);
    lines.push(`  '${templateId}',`);
    lines.push(`  'conditional',`);
    lines.push(`  '${action}',`);
    lines.push(`  ${targetTaskIdsSQL},`);
    lines.push(`  ${targetWidgetIdsSQL},`);
    lines.push(`  '${escapeSQL(JSON.stringify(compoundConditions))}',`);
    lines.push(`  '${escapeSQL(rule.id)}',`);
    lines.push(`  '${escapeSQL(JSON.stringify({ targetWidgetGroupIds: targetWidgetIds }))}'`);
    lines.push(`);`);
  }
  lines.push('');

  // Create due date rules
  lines.push('-- Due Date Rules');
  for (let i = 0; i < dueDateRules.length; i++) {
    const rule = dueDateRules[i];
    const ruleUUID = `e${String(i).padStart(7, '0')}-0000-0000-0000-000000000001`;

    const targetTaskId = taskGroupToUUID.get(rule.targetTaskTemplateGroup.id);
    if (!targetTaskId) continue;

    const source = rule.sourceType === 'ChecklistStartDate' ? 'checklist_start' : 'form_field';
    const sourceWidgetKey = rule.formFieldWidgetGroup
      ? widgetGroupToKey.get(rule.formFieldWidgetGroup.id) || null
      : null;

    const offset = rule.dueOffset;
    let offsetValue = offset.days;
    let offsetUnit = 'days';
    if (offset.hours > 0 && offset.days === 0) {
      offsetValue = offset.hours;
      offsetUnit = 'hours';
    } else if (offset.weeks > 0 && offset.days === 0) {
      offsetValue = offset.weeks;
      offsetUnit = 'weeks';
    }

    const direction = rule.offsetDirection.toLowerCase();

    lines.push(`INSERT INTO template_rules (id, template_id, rule_type, target_task_ids, due_date_source, due_date_source_widget_key, due_date_offset_value, due_date_offset_unit, due_date_direction, due_date_workdays_only, ps_rule_id) VALUES (`);
    lines.push(`  '${ruleUUID}',`);
    lines.push(`  '${templateId}',`);
    lines.push(`  'due_date',`);
    lines.push(`  ARRAY['${targetTaskId}']::uuid[],`);
    lines.push(`  '${source}',`);
    lines.push(`  ${sourceWidgetKey ? `'${escapeSQL(sourceWidgetKey)}'` : 'NULL'},`);
    lines.push(`  ${offsetValue},`);
    lines.push(`  '${offsetUnit}',`);
    lines.push(`  '${direction}',`);
    lines.push(`  ${rule.workdaysOnly},`);
    lines.push(`  '${escapeSQL(rule.id)}'`);
    lines.push(`);`);
  }
  lines.push('');

  // Create assignment rules
  lines.push('-- Assignment Rules');
  for (let i = 0; i < assignmentRules.length; i++) {
    const rule = assignmentRules[i];
    const ruleUUID = `f${String(i).padStart(7, '0')}-0000-0000-0000-000000000001`;

    const targetTaskId = taskGroupToUUID.get(rule.targetTaskTemplateGroup.id);
    if (!targetTaskId) continue;

    const sourceWidgetKey = rule.sourceFormFieldWidgetGroup
      ? widgetGroupToKey.get(rule.sourceFormFieldWidgetGroup.id) || null
      : null;

    lines.push(`INSERT INTO template_rules (id, template_id, rule_type, target_task_ids, assignment_source_widget_key, ps_rule_id) VALUES (`);
    lines.push(`  '${ruleUUID}',`);
    lines.push(`  '${templateId}',`);
    lines.push(`  'assignment',`);
    lines.push(`  ARRAY['${targetTaskId}']::uuid[],`);
    lines.push(`  ${sourceWidgetKey ? `'${escapeSQL(sourceWidgetKey)}'` : 'NULL'},`);
    lines.push(`  '${escapeSQL(rule.id)}'`);
    lines.push(`);`);
  }
  lines.push('');

  // Seed test data
  lines.push('-- Test Users');
  lines.push(`INSERT INTO users (id, email, name, role) VALUES`);
  lines.push(`  ('00000000-0000-0000-0000-000000000001', 'shawn@zonos.com', 'Shawn Roah', 'admin'),`);
  lines.push(`  ('00000000-0000-0000-0000-000000000002', 'ae@zonos.com', 'Demo AE', 'ae'),`);
  lines.push(`  ('00000000-0000-0000-0000-000000000003', 'ob@zonos.com', 'Demo OB Rep', 'ob_rep')`);
  lines.push(`ON CONFLICT (email) DO NOTHING;`);
  lines.push('');

  lines.push('-- Test Project');
  lines.push(`INSERT INTO projects (id, merchant_id, merchant_name, store_url, platform, ae_id, ob_rep_id, template_id, start_date, status) VALUES (`);
  lines.push(`  '10000000-0000-0000-0000-000000000001',`);
  lines.push(`  '5782',`);
  lines.push(`  'Shawn''s Test Store',`);
  lines.push(`  'https://test-store.example.com',`);
  lines.push(`  'Shopify',`);
  lines.push(`  '00000000-0000-0000-0000-000000000002',`);
  lines.push(`  '00000000-0000-0000-0000-000000000003',`);
  lines.push(`  '${templateId}',`);
  lines.push(`  CURRENT_DATE,`);
  lines.push(`  'in_progress'`);
  lines.push(`);`);
  lines.push('');

  const sql = lines.join('\n');
  fs.writeFileSync(OUTPUT_PATH, sql, 'utf-8');

  console.log(`Generated seed migration: ${OUTPUT_PATH}`);
  console.log(`  Templates: 1`);
  console.log(`  Template Tasks: ${tasks.length}`);
  console.log(`  Template Widgets: ${widgetIndex}`);
  console.log(`  Conditional Rules: ${conditionalRules.length}`);
  console.log(`  Due Date Rules: ${dueDateRules.length}`);
  console.log(`  Assignment Rules: ${assignmentRules.length}`);
}

main();
